### ISSUE TITLE
Introduce pre-commit with markdownlint-cli2 hooks

### ISSUE THREAD

**Issue by ns-rse** [RSEToolkit/rse-competencies-toolkit#46]
Very minor really but the [pre-commit](https://pre-commit.com) is a widely used framework for running various hooks such as linting and testing prior to making commits. It also has [pre-commit.ci](https://pre-commit.ci) available for integration with Pull Requests.

Adding this to the repository initially with [markdownlint-cli2](https://github.com/DavidAnson/markdownlint-cli2) as an enable hook and a few of the basic defaults would perhaps be useful.

Happy to do this (have it ready and waiting) but can't currently contribute to this repository nor assign the issue to myself.

**Comment by elichad** [comment]
@ns-rse I don't have the necessary permissions to add you as a collaborator, but if you're able to create a fork and open a PR from there, I can take a look.

**Comment by davehorsfall** [comment]
Hi @ns-rse, I've just added you to the team, so you should have permission to perform these actions. Thanks very much for suggesting. If you create a PR then I'll be very happy to review.
